rsnapshot-program.pl
One liner to get rid of warn output shown below, which occurs because $ENV{PWD} is not set. $ENV{PWD} appears to be erroneous in any case, as it does not update with chdir() which has been called earlier at this point.
sudo rsnapshot -c rsnapshot.conf sync
Use of uninitialized value $linux_lvm_oldpwd in concatenation (.) or string at /usr/bin/rsnapshot line   3720.
Use of uninitialized value $linux_lvm_oldpwd in chdir at /usr/bin/rsnapshot line 3722.
Use of chdir('') or chdir(undef) as chdir() is deprecated at /usr/bin/rsnapshot line 3722.
Logical volume "backups-rsnapshot" successfully removed
Test pass. Note this is a recommit of an older commit I did to master.
=> Use cwd() not $ENV{PWD}

rsnapshot-program.pl
Logging what pid was locked is useful for debugging when bad things
happen to rsnapshot lock files.
=> Log what pid was locked.

rsnapshot-program.pl
The --rsh=... argument to rsync was erroneously quoted when added to the
@rsync_long_args_stack with options set.
Test-Information:
Unit tests pass.
Tested and verified on Debian 7.0
=> Fix --rsh commandline option

.travis.yml, INSTALL, Makefile.am, README, autoclean.sh, autogen.sh, configure.ac, rsnapshot-program.pl
There had been multiple issues to fix also in
compilation/building-system to give travis the ability to build
properly. The progress is still missing, a key, that travis can
automatically deploy to github-releases.
You can see how it will look like at my spam-repository. There are just bogus commits/PRs/releases/tags made.
A bogus PR: https://github.com/bebehei/rsnapshot-clone/pull/1
Check out the releases-page, too!
=> add travis support

rsnapshot-program.pl
Previously empty pid caused call to kill() to die immediately. Now does same as stale pid with minor variation in warnings shown.
@sam-at-github Pls merge this after your verification. It is rebasing, squashing and merging your PR.
closes #13
=> Added handling for empty pid file

rsnapshot-diff.pl
remove trailing slahes on arguments, so that we don't end up with paths like /mnt/backup/daily.0//localhost
=> remove trailing slahes on arguments

rsnapshot-program.pl
according to rsnapshot/sourceforge-issues#48 if you have in your config-file
include_conf `./this_file_gives_out_valid_configlines_on_execution.sh`
You will suffer, that it says:
ERROR: include_conf `./test.sh` - can't find or read file '`./this_file_gives_out_valid_configlines_on_execution.sh`' 
But in fact, it fails, cause `is_valid_script("./this_file_gives_out_valid_configlines_on_execution.sh")` returns false.
Now the error-message differs between a config-file and a config-script.
=> refine the error-message, when sourcing include_conf script fails

configure.ac, rsnapshot-program.pl, t/cmd-post_pre-exec.t.in, t/cmd-post_pre-exec/pre-false-post-false.conf.in, t/cmd-post_pre-exec/pre-false-post-true.conf.in, t/cmd-post_pre-exec/pre-true-post-false.conf.in, t/cmd-post_pre-exec/pre-true-post-true.conf.in
As requested on rsnapshot/sourceforge-issues#47.
For me it makes sense, when cmd_preexec fails, that the backup should not get executed.
Comment on the changeset from the sourceforge-issue: I don't want to add a new configuration-option to this. If users really want to have the backup executed although cmd_preexec fails, they have to `exit(0)` in their script.
@rsnapshot/maintainers What do you think?
=> bail on failing cmd preexec or cmd postexec

configure.ac, rsnapshot.conf.default.in
This is what the Debian package use from February 2011 to detect and prepare LVM stuff in the configuration.
=> Prepare LVM configuration and detect binaries paths

rsnapshot-program.pl
About the commit: I don't really understand the comment in the `else` block (see below), but I think it needs to be updated.
```perl
} else {
print_msg("No directory to delete: $config_vars{'snapshot_root'}/_delete.$$", 5);
}
```
=> fix for #48 -- if($use_lazy_deletes): remove lockfile in any case

Makefile.am, configure.ac
Under OpenSuse, rsnapshot won't build, cause libtool is not needed. and rm of libtoolT fails during build.
=> remove libtool from buildsystem

rsnapshot-program.pl, t/rotate_only_when_0_avail/conf/rotate_only_when_0_avail.conf.in, t/rotate_only_when_0_avail/rotate_only_when_0_avail.t.in
With this bugfix, gaps like a missing <interval>.0 folder will be prevented.
See bug #18.
replace #34
=> Rotate only if there will be a new <interval>.0 folder

ChangeLog, rsnapshot-program.pl
adds a warning, when the verbosity is previously set to a higher
level in a subsequent declaration. This is useful, when you accidentally
set the -v option and define a higher verbosity in your config-file.
closes #47
=> add warning, when setting multiple times verbosity

ChangeLog, rsnapshot-program.pl, t/rsync-exitcode/conf/rsync-exitcode-bad.conf.in, t/rsync-exitcode/conf/rsync-exitcode-good.conf.in, t/rsync-exitcode/rsync-exitcode.t.in
This may be the solution for #102 
I have to test it and get more knowledge about child-processes.
I don't know how it will behave, when rsync closes STDERR and STDOUT and exits before we call waitpid.
=> Grab rsync's exit code

utils/rsnapreport.pl
#95 fixed rsnapreport.pl for newer versions of rsync but broke it for older ones. This PR cherry picked that PR, and fixed it to work with older rsync. Test on:
> lsb_release -r -c; rsync --version | grep version
Release:	7.9
Codename:	wheezy
rsync  version 3.0.9  protocol version 30
and
Release:	8.0
Codename:	jessie
rsync  version 3.1.1  protocol version 31
=> Cherry pick #95 (rsnapreport.pl + rsync >= 3.1.0 bug fix) and update.

rsnapshot-program.pl
A Debian user reported that if /etc/rsnapshot.conf has an LVM backup source followed by non-LVM backup sources, rsnapshot encounter an error. Instead of undefine the trap variable, the patch reset it to 0.
Source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794046
=> Non-LVM backup source breaks after LVM backup source

rsnapshot-program.pl
Consider following example backup endpoint
```
backup	rsync://rsync.samba.org/rsyncftp/	rsync.samba.org/rsyncftp/	+rsync_short_args=-z
```
Before it caused rsnapshot to run rsync with single `"-a -z"` argument and this behavior is definitely incorrect. So, it seems, `+rsync_short_args` never worked properly before.
=> Fixes shortargs appending

t/long_and_short_args/conf/long_and_short_args.conf.in, t/long_and_short_args/conf/long_and_short_args_inline.conf.in, t/long_and_short_args/long_and_short_args.t.in
Simply confirm rsnapshot accepts long|short inline or not  args without blowing up. The test can be elaborated on later. Currently rsnapshot blows up on inline short args, so they currently don'e actually worked. #156 fixes that.
=> Add basic test for long and short args. 

rsnapshot-program.pl
The documentation text in `rsnapshot-program.pl` uses examples with the path `<snapshot_root>/<retain>.0`, except for for one remaining case of `<interval>.0`.  This just changes that one instance of "interval" to "retain" to match the others, so the generated man page is consistent.
=> Update "interval" to "retain" in man page text for consistency

.travis.yml
This is option 1: Re-install fakeroot before building [tested - works fine]
See issue #186.
=> Fix missing fakeroot in latest Travis image

rsnapshot-program.pl
After poking around with source code, I found that `rsync` error codes `23` and`24` are considered "minor warnings" and are not shown when `verbose < 4`.
While for error code `24` this is very sane (as rsync run on "live" filesystem often emits spurious "file has vanished" warnings), it is quite dangerous to ignore error code `23`, as the latter is emitted when something prevented `rsync` to fully scan/transfer the source directory.
For example, trying to rsync a non existent or mispelled remote directory (as by the example above) return *no* warnings on the command line, and this is clearly misleading.
I strongly suggest to change line 4202 from `4` to `2`, restoring "normal" warning weight for error code `23`
=> Restored rsync error code 23 as an important warning

rsnapshot.conf.default.in
per-backup-point args must be comma (only) separated (#225).
=> Fix bad syntax for per-backup-point arg in example config.

docs/HOWTOs/rsnapshot-HOWTO.en.html
&#194;&nbsp; was displaying as "Â ", encoding issue. Tested on latest versions of MS Edge, chrome, firefox.
=> Fixed headers on howto page

rsnapshot-program.pl
Lower verbose level of rsync output to 1.3.x equivalent to work with rsnapreport.pl again.
With the rsnapshot verbose level at 4, rsync's verbose level is far too noisy and rsnapreport.pl shows many bad parsing matches.
This brings it back to the 1.3.x behavior of output level which works with the reporting tool as well.
=> Lower verbose level of rsync output requirement

t/ssh_args/ssh_args.t.in
Bug was introduced with PR #231 (in order to address issue #212)
=> Skip both SSH tests (rather one) if SSH doesn't work

configure.ac, t/backup_exec/conf/backup_exec.conf.in, t/backup_exec/conf/backup_exec_fail.conf.in, t/cmd-post_pre-exec/conf/pre-false-post-false.conf.in, t/cmd-post_pre-exec/conf/pre-false-post-true.conf.in, t/cmd-post_pre-exec/conf/pre-true-post-false.conf.in, t/cmd-post_pre-exec/conf/pre-true-post-true.conf.in, t/configtest/conf/configtest.conf.in, t/rsync-exitcode/conf/rsync-exitcode-bad.conf.in
Offer new options in configure to set the path to true/false or, if not set, search for them
See issue #188. 
(This passes the Travis build `fakeroot` issue as the builds used an older image of Ubuntu)
Personally tested on the systems below.
````bash
All tests successful.
Files=11, Tests=33, 13 wallclock secs ( 0.03 usr  0.01 sys +  1.06 cusr  0.11 csys =  1.21 CPU)
Result: PASS
james@james-ubuntu:~/rsnapshot$ uname -a
Linux james-ubuntu 4.8.0-53-generic \
56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
james@james-ubuntu:~/rsnapshot$ git rev-parse --abbrev-ref HEAD
issue/188-fix-macos-tests
````
````bash
All tests successful.
Files=11, Tests=33, 11 wallclock secs ( 0.05 usr  0.05 sys +  1.42 cusr  0.54 csys =  2.06 CPU)
Result: PASS
$ uname -a
Darwin …
```
=> fix location of true and false binaries on macOS

rsnapshot-program.pl, t/native_cp_al/conf/native_cp_al.conf.in, t/native_cp_al/native_cp_al.t.in
Refs #133. Solves same issue as #177. IMO better than #177 since it's clear why ending slashes are needed and they are only added exactly where they are needed. Also adds includes a test case.
=> Fix for 'rsync_cleanup_after_native_cp_al() only works on directories' fail when sync_first on and cmd_cp not set (#133).

rsnapshot-program.pl
Revert changes from #262 (rm -rf failure case on abnormal termination). Add replacement fix. Ref #282. Confirmed fixed according to informal test case in #282. 
The changes in #262 are in the wrong place in view. It's better to try and normalize file paths further upstream as far as possible, rather than trying to have `rm_rf()` sub, which is used in many places, try and address a specific usage case.
Of course the risk is change further upstream means different downstream parts of code see a different value than they did before. But A. it's only for certain backup destination paths B. Changes are minor C. Fixes this issue.
=> Fix regression in 262

utils/rsnapreport.pl
I encountered several issues when using rsnapreport.
The report header said FILE XFER TIME, but the time value is really the file list transfer time.
If there is a file named rsync in the file list, this confuses rsnapreport. Note that my fix isn't perfect. A pathological filename like "rsync -a" would trip it up.  Nonetheless, it's better than before.
If there was more than one LVM backup point, only the data from the last one would be output, and it would be named ./ rather than something related to the actual backup point. Now each LVM backup point has its own line, and the filesystem name under the SOURCE heading is directly related to the logical volume.
Finally, the code says to change the rsnapshot.conf verbose value to 4 in order to use rsnapreport, but this is not necessary if …
=> fix rsnapreport problems (incorrect header, fail when rsync present, fail with LVM)

rsnapshot-program.pl
This modifies `get_retval`. Under normal circumstances, the exit code is stored in the upper 8 bits of the 16 bit status variable, so it is correct to divide by 256.
However, if Rsync is terminated by a signal, it does not have a normal return code. Instead, the terminating signal is stored in the lower 7 bits and the expected return code (given by a shell) is 128 plus the signal number.
There are some cases where Rsync can be terminated by SIGSEGV, in which case the expected return code is 139. Instead, a floating point value is currently outputted:
```
ERROR: /usr/local/bin/rsync returned 0.54296875 while processing root@my.host.net:/
```
This patch fixes this by checking the equivalent of `WIFSIGNALED` and will instead return 128 + signo.
=> Minor bugfix: Check retval for termination by signal

README.md
Readme still lists the deprecated `interval` key in the conf example. This PR replaces it with the current key `retain`
=> replace deprecated `interval` with `retain` in readme example

README.md
As a new user with a very basic initial setup, this was the biggest gotcha for me. I thought it was prudent to clarify the cross interval rotation upfront.
The cronjobs and the interval settings are set separately and if out of sync, they can lead to very unexpected behavior like all weekly snapshots being many weeks old because the user didn't realize the retention setting for the lower interval had direct bearing on the higher interval snapshot rotation.
=> update readme with info on cross interval rotation

AUTHORS, rsnapshot-program.pl, rsnapshot.conf.default.in, t/numtries/conf/numtries_fail_negative.conf.in, t/numtries/conf/numtries_fail_notanumber.conf.in, t/numtries/conf/numtries_fail_zero.conf.in, t/numtries/conf/numtries_ok.conf.in, t/numtries/numtries.t.in
- Added test cases for rsync_numtries validation
- Fix validation of rsync_numtries = 0, error message, configuration
example and related text.
Bug Report: https://github.com/rsnapshot/rsnapshot/issues/319
=> Fix validation of rsync_numtries = 0

rsnapshot-program.pl
When viewing man pages created by pod2man, it would insert a Unicode en-dash where an ASCII hyphen was necessary for copy-pasting code correctly.
Mostly I fixed this using `C<...>` and indenting literal paragraphs with spaces instead of using `=over` (which is for text not code).
Unfortunately using `C<...>` does add double quotes in the default manpage viewer. `pod2html` translates `C<...>` into `<code>...</code>`. I tried using `B<>` but the troff output for hyphen literals isn't affected by `B<...>` or `F<...>`; they would remain en-dashes when pod2man got through with it.
Other fixes:
- Grammatical issue: s/over-ride/override/
- Add some missing `B<...>` surrounding configuration options when mentioning them
- Use `F<...>` for filename references (e.g. `F</etc/rsnapshot.conf.default>` …
=> Docs: Fix ASCII hyphens getting turned into en-dashes, other styling fixes

rsnapshot-program.pl
The recommended cron job command for `sync_first 1` behaves differently than the non-sync command recommendation:
* `sync_first 0`: "warnings" occurring during the rsync operation do not influence the following "rotate" operation
* `sync_first 1`: "warnings" during "rsnaphot sync" lead to an exit code value 2. The rotation is skipped (`rsnapshot sync && rsnapshot alpha`).
Now the man page mentions this difference in behavior and recommends an adjusted cron job, which preserves the non-sync behavior.
See #338
=> Docs: mention the behavior of "sync" cron job in case of "warnings"

rsnapshot-program.pl
The feature was added in 7f0a553d4585, but it was never documented.
=> Docs: add description for `rsync_numtries` to man page

docs/HOWTOs/rsnapshot-HOWTO.en.md
This is based on #355 (which was re #354), I tidied up the markdown more. I can't find a way to make a pull request on a pull request. 
I think I pretty much kept the commits organized by kinds of task (noted in body of commit). Sometimes I missed things the first time so there is more than 1 commit basically doing related things.  But if something doesn't suit your taste should be easy enough to find and remove.
Summary:
- Normalize headings to use `#` style, start at level 1, and have correct hierarchy per the content
- Remove backslash escapes for underscores and other characters
- code blocks and inline code: 
- correct syntax
- replace italics and bold with code markup where appropriate
- add markup where it is missing
- **note:** I tried to be really careful to adhere to the …
=> Convert howto from html to markdown - tidy markdown

rsnapshot.conf.default.in, utils/README, utils/backup_sqlite.sh
backup_sqlite.sh will backup sqlite3 databases to the current working directory.
recreated from:
https://github.com/rsnapshot/rsnapshot/pull/326
=> Add new backup script for sqlite3 databases

.github/workflows/publish.yml, Makefile.am
Add a Github publish workflow to automate publishing of release to Github (rsnapshot.org is a WIP). Maintainer just needs to update Changelog then push a tag.
Also builds a .deb file. Not meant to replace debian package but just in case Debian package maintainer disappears again. Unfortunately debian package build requires a debian/ directory with a bunch of cruft in it. I cut it back to the bare minimum and does not include a change log because we already have a changelog and maintaining the debian changelog in addition is annoying. Also means the .deb is unsigned because signing would require keep a GPG key in secrets and don't want to do that. Instead release assets are signed with Sigstore signature. Ref #363
=> Add a Github publish workflow

rsnapshot-program.pl
This is the fix suggested in https://github.com/rsnapshot/rsnapshot/issues/373#issuecomment-2989020047
=> Update documentation to clarify that snapshot_root can be a network mount but not SMB/CIFS
